services:
  - type: web
    name: design-rite-staging
    runtime: node
    region: oregon
    plan: starter
    branch: staging
    buildCommand: npm install --force && npm run build
    startCommand: npm run start
    autoDeploy: true
    healthCheckPath: /
    envVars:
      # ========================================
      # ENVIRONMENT
      # ========================================
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_ENVIRONMENT
        value: staging
      - key: ENVIRONMENT
        value: staging
      
      # ========================================
      # SUPABASE (Validation Lab)
      # ========================================
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://ickwrbdpuorzdpzqbqpf.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      
      # ========================================
      # APP URLS
      # ========================================
      - key: NEXT_PUBLIC_APP_URL
        value: https://design-rite-staging.onrender.com
      - key: NEXT_PUBLIC_PRODUCTION_URL
        value: https://design-rite-staging.onrender.com
      - key: NEXT_PUBLIC_SITE_URL
        value: https://design-rite-staging.onrender.com
      
      # ========================================
      # NEXTAUTH
      # ========================================
      - key: NEXTAUTH_URL
        value: https://design-rite-staging.onrender.com
      - key: NEXTAUTH_SECRET
        sync: false
      
      # ========================================
      # AI SERVICES
      # ========================================
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: ASSISTANT_ID
        sync: false
      
      # ========================================
      # STRIPE (Test Mode)
      # ========================================
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      
      # ========================================
      # PORT
      # ========================================
      - key: PORT
        value: 10000
      
      # ========================================
      # FEATURE FLAGS
      # ========================================
      - key: ENABLE_SUBSCRIBER_PORTAL
        value: true
      - key: ENABLE_PRICING_INTELLIGENCE
        value: true
      - key: ENABLE_ADMIN_DASHBOARD
        value: true
      - key: ENABLE_CONVERSION_TRACKING
        value: true
      
      # ========================================
      # RATE LIMITING
      # ========================================
      - key: RATE_LIMIT_ENABLED
        value: true
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 200
      
      # ========================================
      # LOGGING
      # ========================================
      - key: LOG_LEVEL
        value: info
      - key: ENABLE_REQUEST_LOGGING
        value: true
      - key: ENABLE_QUERY_LOGGING
        value: false
      - key: ENABLE_DEBUG_PANEL
        value: false
      
      # ========================================
      # MONITORING
      # ========================================
      - key: ENABLE_ANALYTICS
        value: true
      - key: ENABLE_ERROR_TRACKING
        value: true
      - key: ENABLE_PERFORMANCE_MONITORING
        value: true
      
      # ========================================
      # SECURITY
      # ========================================
      - key: SECURITY_HEADERS_ENABLED
        value: true
      - key: HELMET_ENABLED
        value: true
      - key: CSRF_PROTECTION_ENABLED
        value: true
      
      # ========================================
      # HEALTH CHECK
      # ========================================
      - key: HEALTH_CHECK_ENDPOINT
        value: /api/health
